// Full list of country dialing codes for the registration phone field.
// A plain static array (a few KB gzipped) rendered into a native <select> —
// no phone-validation library, no flag images, so it adds no meaningful weight
// and only loads on /register. Flags are unicode emoji (plain text).
//
// `iso` is the ISO 3166-1 alpha-2 code (used as a stable React key, since dial
// codes are not unique — e.g. +1 covers US, Canada and Caribbean territories).

export type DialCode = { name: string; dial: string; iso: string; flag: string };

export const DIAL_CODES: DialCode[] = [
  { name: "Afghanistan", dial: "+93", iso: "AF", flag: "🇦🇫" },
  { name: "Albania", dial: "+355", iso: "AL", flag: "🇦🇱" },
  { name: "Algeria", dial: "+213", iso: "DZ", flag: "🇩🇿" },
  { name: "Andorra", dial: "+376", iso: "AD", flag: "🇦🇩" },
  { name: "Angola", dial: "+244", iso: "AO", flag: "🇦🇴" },
  { name: "Antigua and Barbuda", dial: "+1", iso: "AG", flag: "🇦🇬" },
  { name: "Argentina", dial: "+54", iso: "AR", flag: "🇦🇷" },
  { name: "Armenia", dial: "+374", iso: "AM", flag: "🇦🇲" },
  { name: "Aruba", dial: "+297", iso: "AW", flag: "🇦🇼" },
  { name: "Australia", dial: "+61", iso: "AU", flag: "🇦🇺" },
  { name: "Austria", dial: "+43", iso: "AT", flag: "🇦🇹" },
  { name: "Azerbaijan", dial: "+994", iso: "AZ", flag: "🇦🇿" },
  { name: "Bahamas", dial: "+1", iso: "BS", flag: "🇧🇸" },
  { name: "Bahrain", dial: "+973", iso: "BH", flag: "🇧🇭" },
  { name: "Bangladesh", dial: "+880", iso: "BD", flag: "🇧🇩" },
  { name: "Barbados", dial: "+1", iso: "BB", flag: "🇧🇧" },
  { name: "Belarus", dial: "+375", iso: "BY", flag: "🇧🇾" },
  { name: "Belgium", dial: "+32", iso: "BE", flag: "🇧🇪" },
  { name: "Belize", dial: "+501", iso: "BZ", flag: "🇧🇿" },
  { name: "Benin", dial: "+229", iso: "BJ", flag: "🇧🇯" },
  { name: "Bhutan", dial: "+975", iso: "BT", flag: "🇧🇹" },
  { name: "Bolivia", dial: "+591", iso: "BO", flag: "🇧🇴" },
  { name: "Bosnia and Herzegovina", dial: "+387", iso: "BA", flag: "🇧🇦" },
  { name: "Botswana", dial: "+267", iso: "BW", flag: "🇧🇼" },
  { name: "Brazil", dial: "+55", iso: "BR", flag: "🇧🇷" },
  { name: "Brunei", dial: "+673", iso: "BN", flag: "🇧🇳" },
  { name: "Bulgaria", dial: "+359", iso: "BG", flag: "🇧🇬" },
  { name: "Burkina Faso", dial: "+226", iso: "BF", flag: "🇧🇫" },
  { name: "Burundi", dial: "+257", iso: "BI", flag: "🇧🇮" },
  { name: "Cambodia", dial: "+855", iso: "KH", flag: "🇰🇭" },
  { name: "Cameroon", dial: "+237", iso: "CM", flag: "🇨🇲" },
  { name: "Canada", dial: "+1", iso: "CA", flag: "🇨🇦" },
  { name: "Cape Verde", dial: "+238", iso: "CV", flag: "🇨🇻" },
  { name: "Central African Republic", dial: "+236", iso: "CF", flag: "🇨🇫" },
  { name: "Chad", dial: "+235", iso: "TD", flag: "🇹🇩" },
  { name: "Chile", dial: "+56", iso: "CL", flag: "🇨🇱" },
  { name: "China", dial: "+86", iso: "CN", flag: "🇨🇳" },
  { name: "Colombia", dial: "+57", iso: "CO", flag: "🇨🇴" },
  { name: "Comoros", dial: "+269", iso: "KM", flag: "🇰🇲" },
  { name: "Congo (Brazzaville)", dial: "+242", iso: "CG", flag: "🇨🇬" },
  { name: "Congo (Kinshasa)", dial: "+243", iso: "CD", flag: "🇨🇩" },
  { name: "Costa Rica", dial: "+506", iso: "CR", flag: "🇨🇷" },
  { name: "Côte d'Ivoire", dial: "+225", iso: "CI", flag: "🇨🇮" },
  { name: "Croatia", dial: "+385", iso: "HR", flag: "🇭🇷" },
  { name: "Cuba", dial: "+53", iso: "CU", flag: "🇨🇺" },
  { name: "Cyprus", dial: "+357", iso: "CY", flag: "🇨🇾" },
  { name: "Czech Republic", dial: "+420", iso: "CZ", flag: "🇨🇿" },
  { name: "Denmark", dial: "+45", iso: "DK", flag: "🇩🇰" },
  { name: "Djibouti", dial: "+253", iso: "DJ", flag: "🇩🇯" },
  { name: "Dominica", dial: "+1", iso: "DM", flag: "🇩🇲" },
  { name: "Dominican Republic", dial: "+1", iso: "DO", flag: "🇩🇴" },
  { name: "Ecuador", dial: "+593", iso: "EC", flag: "🇪🇨" },
  { name: "Egypt", dial: "+20", iso: "EG", flag: "🇪🇬" },
  { name: "El Salvador", dial: "+503", iso: "SV", flag: "🇸🇻" },
  { name: "Equatorial Guinea", dial: "+240", iso: "GQ", flag: "🇬🇶" },
  { name: "Eritrea", dial: "+291", iso: "ER", flag: "🇪🇷" },
  { name: "Estonia", dial: "+372", iso: "EE", flag: "🇪🇪" },
  { name: "Eswatini", dial: "+268", iso: "SZ", flag: "🇸🇿" },
  { name: "Ethiopia", dial: "+251", iso: "ET", flag: "🇪🇹" },
  { name: "Fiji", dial: "+679", iso: "FJ", flag: "🇫🇯" },
  { name: "Finland", dial: "+358", iso: "FI", flag: "🇫🇮" },
  { name: "France", dial: "+33", iso: "FR", flag: "🇫🇷" },
  { name: "Gabon", dial: "+241", iso: "GA", flag: "🇬🇦" },
  { name: "Gambia", dial: "+220", iso: "GM", flag: "🇬🇲" },
  { name: "Georgia", dial: "+995", iso: "GE", flag: "🇬🇪" },
  { name: "Germany", dial: "+49", iso: "DE", flag: "🇩🇪" },
  { name: "Ghana", dial: "+233", iso: "GH", flag: "🇬🇭" },
  { name: "Greece", dial: "+30", iso: "GR", flag: "🇬🇷" },
  { name: "Grenada", dial: "+1", iso: "GD", flag: "🇬🇩" },
  { name: "Guatemala", dial: "+502", iso: "GT", flag: "🇬🇹" },
  { name: "Guinea", dial: "+224", iso: "GN", flag: "🇬🇳" },
  { name: "Guinea-Bissau", dial: "+245", iso: "GW", flag: "🇬🇼" },
  { name: "Guyana", dial: "+592", iso: "GY", flag: "🇬🇾" },
  { name: "Haiti", dial: "+509", iso: "HT", flag: "🇭🇹" },
  { name: "Honduras", dial: "+504", iso: "HN", flag: "🇭🇳" },
  { name: "Hong Kong", dial: "+852", iso: "HK", flag: "🇭🇰" },
  { name: "Hungary", dial: "+36", iso: "HU", flag: "🇭🇺" },
  { name: "Iceland", dial: "+354", iso: "IS", flag: "🇮🇸" },
  { name: "India", dial: "+91", iso: "IN", flag: "🇮🇳" },
  { name: "Indonesia", dial: "+62", iso: "ID", flag: "🇮🇩" },
  { name: "Iran", dial: "+98", iso: "IR", flag: "🇮🇷" },
  { name: "Iraq", dial: "+964", iso: "IQ", flag: "🇮🇶" },
  { name: "Ireland", dial: "+353", iso: "IE", flag: "🇮🇪" },
  { name: "Israel", dial: "+972", iso: "IL", flag: "🇮🇱" },
  { name: "Italy", dial: "+39", iso: "IT", flag: "🇮🇹" },
  { name: "Jamaica", dial: "+1", iso: "JM", flag: "🇯🇲" },
  { name: "Japan", dial: "+81", iso: "JP", flag: "🇯🇵" },
  { name: "Jordan", dial: "+962", iso: "JO", flag: "🇯🇴" },
  { name: "Kazakhstan", dial: "+7", iso: "KZ", flag: "🇰🇿" },
  { name: "Kenya", dial: "+254", iso: "KE", flag: "🇰🇪" },
  { name: "Kiribati", dial: "+686", iso: "KI", flag: "🇰🇮" },
  { name: "Kosovo", dial: "+383", iso: "XK", flag: "🇽🇰" },
  { name: "Kuwait", dial: "+965", iso: "KW", flag: "🇰🇼" },
  { name: "Kyrgyzstan", dial: "+996", iso: "KG", flag: "🇰🇬" },
  { name: "Laos", dial: "+856", iso: "LA", flag: "🇱🇦" },
  { name: "Latvia", dial: "+371", iso: "LV", flag: "🇱🇻" },
  { name: "Lebanon", dial: "+961", iso: "LB", flag: "🇱🇧" },
  { name: "Lesotho", dial: "+266", iso: "LS", flag: "🇱🇸" },
  { name: "Liberia", dial: "+231", iso: "LR", flag: "🇱🇷" },
  { name: "Libya", dial: "+218", iso: "LY", flag: "🇱🇾" },
  { name: "Liechtenstein", dial: "+423", iso: "LI", flag: "🇱🇮" },
  { name: "Lithuania", dial: "+370", iso: "LT", flag: "🇱🇹" },
  { name: "Luxembourg", dial: "+352", iso: "LU", flag: "🇱🇺" },
  { name: "Macau", dial: "+853", iso: "MO", flag: "🇲🇴" },
  { name: "Madagascar", dial: "+261", iso: "MG", flag: "🇲🇬" },
  { name: "Malawi", dial: "+265", iso: "MW", flag: "🇲🇼" },
  { name: "Malaysia", dial: "+60", iso: "MY", flag: "🇲🇾" },
  { name: "Maldives", dial: "+960", iso: "MV", flag: "🇲🇻" },
  { name: "Mali", dial: "+223", iso: "ML", flag: "🇲🇱" },
  { name: "Malta", dial: "+356", iso: "MT", flag: "🇲🇹" },
  { name: "Marshall Islands", dial: "+692", iso: "MH", flag: "🇲🇭" },
  { name: "Mauritania", dial: "+222", iso: "MR", flag: "🇲🇷" },
  { name: "Mauritius", dial: "+230", iso: "MU", flag: "🇲🇺" },
  { name: "Mexico", dial: "+52", iso: "MX", flag: "🇲🇽" },
  { name: "Micronesia", dial: "+691", iso: "FM", flag: "🇫🇲" },
  { name: "Moldova", dial: "+373", iso: "MD", flag: "🇲🇩" },
  { name: "Monaco", dial: "+377", iso: "MC", flag: "🇲🇨" },
  { name: "Mongolia", dial: "+976", iso: "MN", flag: "🇲🇳" },
  { name: "Montenegro", dial: "+382", iso: "ME", flag: "🇲🇪" },
  { name: "Morocco", dial: "+212", iso: "MA", flag: "🇲🇦" },
  { name: "Mozambique", dial: "+258", iso: "MZ", flag: "🇲🇿" },
  { name: "Myanmar", dial: "+95", iso: "MM", flag: "🇲🇲" },
  { name: "Namibia", dial: "+264", iso: "NA", flag: "🇳🇦" },
  { name: "Nauru", dial: "+674", iso: "NR", flag: "🇳🇷" },
  { name: "Nepal", dial: "+977", iso: "NP", flag: "🇳🇵" },
  { name: "Netherlands", dial: "+31", iso: "NL", flag: "🇳🇱" },
  { name: "New Zealand", dial: "+64", iso: "NZ", flag: "🇳🇿" },
  { name: "Nicaragua", dial: "+505", iso: "NI", flag: "🇳🇮" },
  { name: "Niger", dial: "+227", iso: "NE", flag: "🇳🇪" },
  { name: "Nigeria", dial: "+234", iso: "NG", flag: "🇳🇬" },
  { name: "North Korea", dial: "+850", iso: "KP", flag: "🇰🇵" },
  { name: "North Macedonia", dial: "+389", iso: "MK", flag: "🇲🇰" },
  { name: "Norway", dial: "+47", iso: "NO", flag: "🇳🇴" },
  { name: "Oman", dial: "+968", iso: "OM", flag: "🇴🇲" },
  { name: "Pakistan", dial: "+92", iso: "PK", flag: "🇵🇰" },
  { name: "Palau", dial: "+680", iso: "PW", flag: "🇵🇼" },
  { name: "Palestine", dial: "+970", iso: "PS", flag: "🇵🇸" },
  { name: "Panama", dial: "+507", iso: "PA", flag: "🇵🇦" },
  { name: "Papua New Guinea", dial: "+675", iso: "PG", flag: "🇵🇬" },
  { name: "Paraguay", dial: "+595", iso: "PY", flag: "🇵🇾" },
  { name: "Peru", dial: "+51", iso: "PE", flag: "🇵🇪" },
  { name: "Philippines", dial: "+63", iso: "PH", flag: "🇵🇭" },
  { name: "Poland", dial: "+48", iso: "PL", flag: "🇵🇱" },
  { name: "Portugal", dial: "+351", iso: "PT", flag: "🇵🇹" },
  { name: "Qatar", dial: "+974", iso: "QA", flag: "🇶🇦" },
  { name: "Romania", dial: "+40", iso: "RO", flag: "🇷🇴" },
  { name: "Russia", dial: "+7", iso: "RU", flag: "🇷🇺" },
  { name: "Rwanda", dial: "+250", iso: "RW", flag: "🇷🇼" },
  { name: "Saint Kitts and Nevis", dial: "+1", iso: "KN", flag: "🇰🇳" },
  { name: "Saint Lucia", dial: "+1", iso: "LC", flag: "🇱🇨" },
  { name: "Saint Vincent and the Grenadines", dial: "+1", iso: "VC", flag: "🇻🇨" },
  { name: "Samoa", dial: "+685", iso: "WS", flag: "🇼🇸" },
  { name: "San Marino", dial: "+378", iso: "SM", flag: "🇸🇲" },
  { name: "São Tomé and Príncipe", dial: "+239", iso: "ST", flag: "🇸🇹" },
  { name: "Saudi Arabia", dial: "+966", iso: "SA", flag: "🇸🇦" },
  { name: "Senegal", dial: "+221", iso: "SN", flag: "🇸🇳" },
  { name: "Serbia", dial: "+381", iso: "RS", flag: "🇷🇸" },
  { name: "Seychelles", dial: "+248", iso: "SC", flag: "🇸🇨" },
  { name: "Sierra Leone", dial: "+232", iso: "SL", flag: "🇸🇱" },
  { name: "Singapore", dial: "+65", iso: "SG", flag: "🇸🇬" },
  { name: "Slovakia", dial: "+421", iso: "SK", flag: "🇸🇰" },
  { name: "Slovenia", dial: "+386", iso: "SI", flag: "🇸🇮" },
  { name: "Solomon Islands", dial: "+677", iso: "SB", flag: "🇸🇧" },
  { name: "Somalia", dial: "+252", iso: "SO", flag: "🇸🇴" },
  { name: "South Africa", dial: "+27", iso: "ZA", flag: "🇿🇦" },
  { name: "South Korea", dial: "+82", iso: "KR", flag: "🇰🇷" },
  { name: "South Sudan", dial: "+211", iso: "SS", flag: "🇸🇸" },
  { name: "Spain", dial: "+34", iso: "ES", flag: "🇪🇸" },
  { name: "Sri Lanka", dial: "+94", iso: "LK", flag: "🇱🇰" },
  { name: "Sudan", dial: "+249", iso: "SD", flag: "🇸🇩" },
  { name: "Suriname", dial: "+597", iso: "SR", flag: "🇸🇷" },
  { name: "Sweden", dial: "+46", iso: "SE", flag: "🇸🇪" },
  { name: "Switzerland", dial: "+41", iso: "CH", flag: "🇨🇭" },
  { name: "Syria", dial: "+963", iso: "SY", flag: "🇸🇾" },
  { name: "Taiwan", dial: "+886", iso: "TW", flag: "🇹🇼" },
  { name: "Tajikistan", dial: "+992", iso: "TJ", flag: "🇹🇯" },
  { name: "Tanzania", dial: "+255", iso: "TZ", flag: "🇹🇿" },
  { name: "Thailand", dial: "+66", iso: "TH", flag: "🇹🇭" },
  { name: "Timor-Leste", dial: "+670", iso: "TL", flag: "🇹🇱" },
  { name: "Togo", dial: "+228", iso: "TG", flag: "🇹🇬" },
  { name: "Tonga", dial: "+676", iso: "TO", flag: "🇹🇴" },
  { name: "Trinidad and Tobago", dial: "+1", iso: "TT", flag: "🇹🇹" },
  { name: "Tunisia", dial: "+216", iso: "TN", flag: "🇹🇳" },
  { name: "Turkey", dial: "+90", iso: "TR", flag: "🇹🇷" },
  { name: "Turkmenistan", dial: "+993", iso: "TM", flag: "🇹🇲" },
  { name: "Tuvalu", dial: "+688", iso: "TV", flag: "🇹🇻" },
  { name: "Uganda", dial: "+256", iso: "UG", flag: "🇺🇬" },
  { name: "Ukraine", dial: "+380", iso: "UA", flag: "🇺🇦" },
  { name: "United Arab Emirates", dial: "+971", iso: "AE", flag: "🇦🇪" },
  { name: "United Kingdom", dial: "+44", iso: "GB", flag: "🇬🇧" },
  { name: "United States", dial: "+1", iso: "US", flag: "🇺🇸" },
  { name: "Uruguay", dial: "+598", iso: "UY", flag: "🇺🇾" },
  { name: "Uzbekistan", dial: "+998", iso: "UZ", flag: "🇺🇿" },
  { name: "Vanuatu", dial: "+678", iso: "VU", flag: "🇻🇺" },
  { name: "Vatican City", dial: "+379", iso: "VA", flag: "🇻🇦" },
  { name: "Venezuela", dial: "+58", iso: "VE", flag: "🇻🇪" },
  { name: "Vietnam", dial: "+84", iso: "VN", flag: "🇻🇳" },
  { name: "Yemen", dial: "+967", iso: "YE", flag: "🇾🇪" },
  { name: "Zambia", dial: "+260", iso: "ZM", flag: "🇿🇲" },
  { name: "Zimbabwe", dial: "+263", iso: "ZW", flag: "🇿🇼" },
];

/** Default selection for the registration form (context: mostly Pakistan). */
export const DEFAULT_DIAL_ISO = "PK";
